import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";


const Home: NextPage = () => {
  const { data } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1 className="text-6xl font-bold">
          Welcome to <b>.ease</b>
          {data && (
            <p>
              {data.user.surname} {data.user.name}{" "}
            </p>
          )}
        </h1>
      </main>
    </>
  );
};

export default Home;
